import {
  FiAward,
  FiBarChart2,
  FiBookOpen,
  FiBriefcase,
  FiCalendar,
  FiCheckCircle,
  FiClock,
  FiCode,
  FiCpu,
  FiDatabase,
  FiEdit3,
  FiGitBranch,
  FiGlobe,
  FiHeart,
  FiHome,
  FiLayers,
  FiMail,
  FiMessageSquare,
  FiPhone,
  FiSend,
  FiServer,
  FiSettings,
  FiShare2,
  FiShield,
  FiStar,
  FiTarget,
  FiTool,
  FiTrendingUp,
  FiUsers,
  FiZap,
} from "react-icons/fi";

// String-key registry so content (services, skills, etc.) can be stored as
// plain JSON and edited without touching component code. Add new icons here
// as needed, then reference the key in the JSON content files.
export const iconRegistry = {
  award: FiAward,
  barChart: FiBarChart2,
  bookOpen: FiBookOpen,
  briefcase: FiBriefcase,
  calendar: FiCalendar,
  checkCircle: FiCheckCircle,
  clock: FiClock,
  code: FiCode,
  cpu: FiCpu,
  database: FiDatabase,
  edit: FiEdit3,
  gitBranch: FiGitBranch,
  globe: FiGlobe,
  heart: FiHeart,
  home: FiHome,
  layers: FiLayers,
  mail: FiMail,
  message: FiMessageSquare,
  phone: FiPhone,
  send: FiSend,
  server: FiServer,
  settings: FiSettings,
  share: FiShare2,
  shield: FiShield,
  star: FiStar,
  target: FiTarget,
  tool: FiTool,
  trending: FiTrendingUp,
  users: FiUsers,
  zap: FiZap,
} as const;

export type IconKey = keyof typeof iconRegistry;
